### ISSUE TITLE
No module named 'termios' on Windows

### ISSUE THREAD

**Issue by waynebowie99** [rcarriga/vim-ultest#115]
**Describe the bug**
On first load of any file I get this error message and from there no commands seem to do anything
I'm on Windows 10 using C# and the dotnet test runner
```
error caught in notification handler 'C:/Users/wayneb/AppData/Local/nvim-data/site/pack/packer/start/vim-ultest/rplugin/python3/ultest:function:_ultest_update_positions [['Jobs.Tests\\Controllers\\JobTrackerControllerShould.cs']]'
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pynvim\plugin\host.py", line 140, in _on_notification
    handler(*args)
  File "C:\Python310\lib\site-packages\pynvim\plugin\host.py", line 89, in _wrap_delayed_function
    self._discover_functions(plugin, module_handlers, path, False)
  File "C:\Python310\lib\site-packages\pynvim\plugin\host.py", line 212, in _discover_functions
    for _, fn in inspect.getmembers(obj, predicate):
  File "C:\Python310\lib\inspect.py", line 469, in getmembers
    value = getattr(object, key)
  File "C:/Users/wayneb/AppData/Local/nvim-data/site/pack/packer/start/vim-ultest/rplugin/python3\ultest\__init__.py", line 80, in handler
    from .handler import HandlerFactory
  File "C:\Users/wayneb/AppData/Local/nvim-data/site/pack/packer/start/vim-ultest/rplugin/python3\ultest\handler\__init__.py", line 11, in <module>
    from .runner import PositionRunner, ProcessManager
  File "C:\Users/wayneb/AppData/Local/nvim-data/site/pack/packer/start/vim-ultest/rplugin/python3\ultest\handler\runner\__init__.py", line 9, in <module>
    from .processes import ProcessManager
  File "C:\Users/wayneb/AppData/Local/nvim-data/site/pack/packer/start/vim-ultest/rplugin/python3\ultest\handler\runner\processes.py", line 11, in <module>
    from .handle import ProcessIOHandle
  File "C:\Users/wayneb/AppData/Local/nvim-data/site/pack/packer/start/vim-ultest/rplugin/python3\ultest\handler\runner\handle.py", line 3, in <module>
    import pty
  File "C:\Python310\lib\pty.py", line 12, in <module>
    import tty
  File "C:\Python310\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'

Error: vim-ultest encountered an unknown error on startup Vim(let):Error invoking 'C:/Users/wayneb/AppData/Local/nvim-data/site/pack/packer/start/vim-ultest/rplugin/python3/ultest:function:_ultest_get_nearest_test' on channel 6 (python3-rplugin-host):^@no request handler registered for "C:/Users/wayneb/AppData/Local/nvim-data/site/pack/packer/start/vim-ultest/rplugin/python3/ultest:function:_ultest_get_nearest_test"
Error: vim-ultest encountered an unknown error on startup Vim(let):Error invoking 'C:/Users/wayneb/AppData/Local/nvim-data/site/pack/packer/start/vim-ultest/rplugin/python3/ultest:function:_ultest_get_nearest_test' on channel 6 (python3-rplugin-host):^@no request handler registered for "C:/Users/wayneb/AppData/Local/nvim-data/site/pack/packer/start/vim-ultest/rplugin/python3/ultest:function:_ultest_get_nearest_test"
```

**Comment by DasOhmoff** [comment]
I have this very same issue

**Comment by rcarriga** [comment]
Same as #71, happy to take a PR to fix this but I don't have a windows machine to develop on. Closing to keep discussion in one place
