### ISSUE TITLE
Cannot run tests (pytest)

### ISSUE THREAD

**Issue by HiPhish** [rcarriga/vim-ultest#50]
**Describe the bug**

I have a test file written in Python using pytest as the test runner. Whenever I execute `:Ultest` or `:UltestNearest` I get a Neovim error. Running the test with `:TestFile` or `TestNearest` however works fine. Here is the error:

```
error caught in async handler '/home/hiphish/.local/share/nvim/site-packages/vim-ultest/rplugin/python3/ultest:functi
on:_ultest_run_nearest [[0, 'test_pydantic.py']]'
Traceback (most recent call last):
  File "/home/hiphish/.local/share/nvim/site-packages/vim-ultest/rplugin/python3/ultest/__init__.py", line 83, in _ru
n_nearest
    self.handler.run_nearest(*args)
  File "/home/hiphish/.local/share/nvim/site-packages/vim-ultest/rplugin/python3/ultest/handler/__init__.py", line 14
8, in run_nearest
    self._runner.run(
  File "/home/hiphish/.local/share/nvim/site-packages/vim-ultest/rplugin/python3/ultest/handler/runner/__init__.py",
line 46, in run
    self._run_group(tree, file_tree, file_name, on_start, on_finish, env)
  File "/home/hiphish/.local/share/nvim/site-packages/vim-ultest/rplugin/python3/ultest/handler/runner/__init__.py",
line 168, in _run_group
    cmd = self._vim.sync_call("ultest#adapter#build_cmd", tree[0], scope)
  File "/home/hiphish/.local/share/nvim/site-packages/vim-ultest/rplugin/python3/ultest/vim_client/__init__.py", line
 121, in sync_call
    return self._eval(expr, sync=True)
  File "/home/hiphish/.local/share/nvim/site-packages/vim-ultest/rplugin/python3/ultest/vim_client/__init__.py", line
 134, in _eval
    return self._vim.eval(expr, async_=not sync)
  File "/home/hiphish/.local/lib/python3.9/site-packages/pynvim/api/nvim.py", line 295, in eval
    return self.request('nvim_eval', string, **kwargs)
  File "/home/hiphish/.local/lib/python3.9/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/hiphish/.local/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim(let):E118: Too many arguments for function: test#base#build_args
```

**To Reproduce**
Create a file `test_test.py` with the following contents:

```python
def test_numeric_inequality():
    a = 2
    b = 3
    assert a != b


def test_numeric_equality():
    a = 3
    b = 3
    assert a == b
```

Place the cursor on either test function and execute `:Ultest` or `:UltestNearest`.

**Additional context**
- Neovim version v0.5.0-dev+1360-ga7205e2b7 (nightly)
- pynvim version 0.4.3 (from pip)
- Python version 3.9
- OS: [Void Linux](https://voidlinux.org/)
- Log file: [vim-ultest.log](https://github.com/rcarriga/vim-ultest/files/6644345/vim-ultest.log)

**Comment by rcarriga** [comment]
This is a very odd error, as this is executed on every test. I can't reproduce this, and can't see anything wrong in the logs. Are you running the latest vim-test with no modifications? If so I'm afraid I can't figure this out any further without an init.vim to reproduce locally

**Comment by HiPhish** [comment]
I have created a bare minimum `init.vim` file:

```vim
let &rtp = stdpath('data') .. '/site-packages/vim-test' .. ',' .. &rtp
let &rtp = stdpath('data') .. '/site-packages/vim-ultest' .. ',' .. &rtp
```

Now I run Neovim in a shell with the new configuration and without any traces of my own

```sh
XDG_CONFIG_HOME=~/config nvim test_test.py
```

I get the exact same error as before.

**Comment by rcarriga** [comment]
I still don't any error with that config. Can you confirm the latest commit that you have for vim-test? Are you using any custom version?

**Comment by HiPhish** [comment]
OK, it was my fault after all, I had vim-test twice in my plugin list, and the other entry had checked out a different branch. Sorry for wasting your time.
